# Form implementation generated from reading ui file 'confirm_form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from database import del_station

class Ui_DialogConfirmationForm(object):
    def setupUi(self, DialogConfirmationForm, sharing_dict):
        self.sharing_dict = sharing_dict
        DialogConfirmationForm.setObjectName("DialogConfirmationForm")
        DialogConfirmationForm.resize(413, 117)
        DialogConfirmationForm.setWindowTitle("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogConfirmationForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=DialogConfirmationForm)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.widget = QtWidgets.QWidget(parent=DialogConfirmationForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(212, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout.addWidget(self.pushButtonConfirm)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout_2.addWidget(self.widget)
        self.pushButtonConfirm.clicked.connect(lambda: del_station(self.sharing_dict['radio_del_candidate_url']))

        self.retranslateUi(DialogConfirmationForm)
        QtCore.QMetaObject.connectSlotsByName(DialogConfirmationForm)

    def retranslateUi(self, DialogConfirmationForm):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("DialogConfirmationForm",
                                      f"Видалити? {self.sharing_dict['radio_del_candidate_name']} "))
        self.pushButtonConfirm.setText(_translate("DialogConfirmationForm", "Видалити"))
        self.pushButtonCancel.setText(_translate("DialogConfirmationForm", "Скасувати"))

    def del_station(self):
        del_station(self.sharing_dict['radio_del_candidate_url'])




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogConfirmationForm = QtWidgets.QDialog()
    ui = Ui_DialogConfirmationForm()
    ui.setupUi(DialogConfirmationForm, sharing_dict=[])
    DialogConfirmationForm.show()
    sys.exit(app.exec())
