class MyThemes:
    white_central_widget = ("QWidget {\n "
                            "    background: rgb(250, 250, 250);\n "
                            "    color: rgb(30, 30, 30);}\n"
                            "\n"
                            "QTabWidget::pane { \n"
                            "    border: 2px solid rgb(230, 230, 230);\n"
                            "    top: -2px; }\n"
                            "\n"
                            "QTabBar::tab {\n"
                            "    background: rgb(230, 230, 230);}\n"
                            "\n"
                            "QTabBar::tab:selected {\n"
                            "    background: rgb(250, 250, 250);}\n"
                            "\n"
                            "QFrame {\n"
                            "    background: rgb(250, 250, 250);}\n"
                            "\n"
                            "QLabel{\n"
                            "    font-size: 20px;}\n"
                            "\n"
                            "QLineEdit {\n"
                            "    font-size: 20px;\n"
                            "    border: 1px solid rgb(100, 100, 100);\n"
                            "    border-radius: 4px;}\n"
                            "\n"
                            "QLineEdit:hover {\n"
                            "    background: rgb(220, 230, 240);}\n"
                            "\n"
                            "QComboBox {\n"
                            "    background-color: rgb(235, 235, 235);\n"
                            "    font-size: 20px;\n"
                            "    border: 1px solid rgb(150, 150, 150);\n"
                            "    border-radius: 3px;}\n"
                            "\n"
                            "QComboBox QAbstractItemView {\n"
                            "    background-color: rgb(250, 250, 250);\n"
                            "    border: 1px solid gray;}\n"
                            "\n"
                            "QComboBox:hover {\n"
                            "    background: rgb(220, 230, 240);}\n"
                            "\n"
                            "QComboBox::drop-down {\n"
                            "    background: rgb(200, 200, 200);}\n"
                            "\n"
                            "QComboBox::down-arrow {\n"
                            "    width: 6px;\n"
                            "    height: 16px;\n"
                            "    background-color: rgb(160, 160, 160);}\n"
                            "\n"
                            "QCheckBox {\n"
                            "    font-size: 20px;}\n"
                            "\n"
                            "QSpinBox {\n"
                            "    font-size: 20px;}\n"
                            "\n"
                            "QSpinBox:hover {\n"
                            "    background: rgb(220, 230, 240);}\n"
                            "\n"
                            "QPushButton {\n"
                            "    min-height: 30px;\n"
                            "    font-size: 20px;\n"
                            "    color: rgb(20, 20, 20);\n"
                            "    border: 1px solid rgb(200, 200, 200);\n"
                            "    border-radius: 3px;\n"
                            "    background-color: rgb(230, 230, 230);}\n"
                            "\n"
                            "QPushButton:hover {\n"
                            "    color: black;\n"
                            "    background: rgb(220, 230, 240);\n"
                            "    border: 1px solid rgb(100, 100 ,100)}\n"
                            "\n"
                            "QToolButton {\n"
                            "    font-size: 20px;\n"
                            "    color: rgb(20, 20, 20);\n"
                            "    border: 1px solid rgb(200, 200, 200);\n"
                            "    border-radius: 3px;\n"
                            "    background-color: rgb(230, 230, 230);}\n"
                            "\n"
                            "QToolButton:hover {\n"
                            "    color: black;\n"
                            "    border: 1px solid rgb(100, 100 ,100)}\n"
                            "\n"
                            "QRadioButton{\n"
                            "    font-size: 16px;}\n"
                            "\n")
    white_widget_18 = ("QWidget {\n"
                       "    background: rgb(240, 240, 240);}\n"
                       "\n"
                       "QLabel {\n"
                       "    font-size: 20px;}\n"
                       "\n"
                       "QLineEdit {\n"
                       "    font-size: 20px;\n"
                       "    border: 1px solid rgb(100, 100, 100);\n"
                       "    border-radius: 4px;}\n"
                       "\n"
                       "QLineEdit:hover {\n"
                       "    background: rgb(220, 230, 240);}\n"
                       "\n"
                       "QComboBox {\n"
                       "    background-color: rgb(235, 235, 235);\n"
                       "    font-size: 20px;\n"
                       "    border: 1px solid rgb(150, 150, 150);\n"
                       "    border-radius: 3px;}\n"
                       "\n"
                       "QComboBox QAbstractItemView {\n"
                       "    background-color: rgb(250, 250, 250);\n"
                       "    border: 1px solid gray;}\n"
                       "\n"
                       "QComboBox:hover {\n"
                       "    background: rgb(220, 230, 240);}\n"
                       "\n"
                       "QComboBox::drop-down {\n"
                       "    background: rgb(200, 200, 200);}\n"
                       "\n"
                       "QComboBox::down-arrow {\n"
                       "    width: 6px;\n"
                       "    height: 16px;\n"
                       "    background-color: rgb(160, 160, 160);}")
    white_frame_4 = ("QFrame {\n"
                     "    background: rgb(220,220, 220);\n"
                     "    border: 0px solid grey;\n"
                     "    border-radius: 9px;}\n"
                     "\n"
                     "QCheckBox {\n"
                     "    font-size: 20px;\n"
                     "    background: rgb(220, 220, 220);}\n"
                     "\n"
                     "QPushButton {\n"
                     "    min-height: 30px;\n"
                     "    font-size: 20px;\n"
                     "    color: white;\n"
                     "    border-radius: 8px;\n"
                     "    background-color: rgb(50, 50, 50);}\n"
                     "\n"
                     "QPushButton:hover {\n"
                     "    color: white;\n"
                     "    background-color: rgb(50, 50, 50);}\n"
                     "\n"
                     "QSlider {\n"
                     "    min-height: 20px;\n"
                     "    background: rgb(220, 220, 220);}\n"
                     "\n"
                     "QSlider::groove:horizontal {\n"
                     "    border: 0px;\n"
                     "    background: rgb(200, 200, 200);\n"
                     "    height: 20px;\n"
                     "    border-radius: 10px;}\n"
                     "\n"
                     "QSlider::handle {\n"
                     "    background: rgb(55, 55, 55);\n"
                     "    height: 20px;\n"
                     "    width: 20px;\n"
                     "    border-radius: 10px;}\n"
                     "\n"
                     "QSlider::sub-page:horizontal {\n"
                     "    background: rgb(100, 100, 100);\n"
                     "    border-top-left-radius: 10px;\n"
                     "    border-bottom-left-radius: 10px;}")
    black_central_widget = ("QWidget {\n"
                            "    background: rgb(30, 30, 30);\n"
                            "    color: rgb(230, 230, 230);}\n"
                            "\n"
                            "QTabWidget::pane { \n"
                            "    border: 3px solid rgb(100, 100, 100);\n"
                            "    top: -3px; }\n"
                            "\n"
                            "QTabBar::tab {\n"
                            "    background: rgb(40, 40, 40);}\n"
                            "\n"
                            "QTabBar::tab:selected {\n"
                            "    background: rgb(80,80,80);}\n"
                            "\n"
                            "QFrame {\n"
                            "    background: rgb(30, 30, 30);\n"
                            "    border-radius: 3px;}\n"
                            "\n"
                            "QLabel {\n"
                            "    font-size: 20px;}\n"
                            "\n"
                            "QLineEdit {\n"
                            "    font-size: 20px;\n"
                            "    border: 1px solid rgb(100, 100, 100);\n"
                            "    border-radius: 4px;}\n"
                            "\n"
                            "QLineEdit:hover {\n"
                            "    background: rgb(100, 100, 100);}\n"
                            "\n"
                            "QComboBox {\n"
                            "    font-size: 20px;\n"
                            "    border: 1px solid rgb(100, 100, 100);\n"
                            "    border-radius: 4px;}\n"
                            "\n"
                            "QComboBox QAbstractItemView {\n"
                            "    background-color: rgb(50, 50, 50);\n"
                            "    border: 1px solid gray;}\n"
                            "\n"
                            "QComboBox:hover {\n"
                            "    background: rgb(100, 100, 100);}\n"
                            "\n"
                            "QComboBox::drop-down {\n"
                            "    background: rgb(100, 100, 100);}\n"
                            "\n"
                            "QComboBox::down-arrow {\n"
                            "    width: 6px;\n"
                            "    height: 16px;\n"
                            "    background-color: rgb(160, 160, 30);}\n"
                            "\n"
                            "QCheckBox {\n"
                            "    font-size: 20px;}\n"
                            "\n"
                            "QSpinBox {\n"
                            "    font-size: 20px;}\n"
                            "\n"
                            "QPushButton {\n"
                            "    min-height: 30px;\n"
                            "    font-size: 20px;\n"
                            "    color: white;\n"
                            "    border-radius: 4px;\n"
                            "    background-color: rgb(50, 50, 50);}\n"
                            "\n"
                            "QPushButton:hover {\n"
                            "    color: white;\n"
                            "    border: 1px solid white;\n"
                            "    background-color: rgb(100, 100, 100);}"
                            "\n"
                            "QToolButton {\n"
                            "    font-size: 20px;\n"
                            "    color: white;\n"
                            "    border-radius: 4px;\n"
                            "    background-color: rgb(50, 50, 50);}\n"
                            "\n"
                            "QToolButton:hover {\n"
                            "    color: white;\n"
                            "    background-color: rgb(100, 100, 100);}\n"
                            "\n"
                            "QRadioButton {\n"
                            "    font-size: 16px;}\n"
                            "\n"
                            "QHeaderView::section{\n"
                            "    background-color: rgb(100, 100, 100)}")
    black_widget_18 = ("QWidget {\n"
                       "    background: rgb(40, 40, 40);\n"
                       "    border: 0px solid grey;\n"
                       "    border-radius: 9px;}\n"
                       "\n"
                       "QLineEdit {\n"
                       "    background-color: rgb(30, 30, 30);\n"
                       "    font-size: 20px;\n"
                       "    border: 1px solid rgb(100, 100, 100);\n"
                       "    border-radius: 4px;}\n"
                       "\n"
                       "QLineEdit:hover {\n"
                       "    background: rgb(100, 100, 100);}\n"
                       "\n"
                       "QComboBox {\n"
                       "    background-color: rgb(30, 30, 30);\n"
                       "    font-size: 20px;\n"
                       "    border: 1px solid rgb(100, 100, 100);\n"
                       "    border-radius: 4px;}\n"
                       "\n"
                       "QComboBox:hover {\n"
                       "    background: rgb(100, 100, 100);}\n"
                       "\n"
                       "QComboBox::drop-down {\n"
                       "    background: rgb(100, 100, 100);}\n"
                       "\n"
                       "QComboBox::down-arrow {\n"
                       "    width: 6px;\n"
                       "    height: 16px;\n"
                       "    background-color: rgb(160, 160, 30);}")
    black_frame_4 = ("QFrame {\n"
                     "    background: rgb(40, 40, 40);\n"
                     "    border: 0px solid grey;\n"
                     "    border-radius: 9px;}\n"
                     "\n"
                     "QCheckBox {\n"
                     "    font-size: 20px;\n"
                     "    background: rgb(40, 40, 40);}\n"
                     "\n"
                     "QPushButton {\n"
                     "    min-height: 30px;\n"
                     "    font-size: 20px;\n"
                     "    color: white;\n"
                     "    border-radius: 4px;\n"
                     "    background-color: rgb(100, 100, 100);}\n"
                     "\n"
                     "QPushButton:hover {\n"
                     "    color: white;\n"
                     "    background-color: rgb(50, 50, 50);}\n"
                     "\n"
                     "QSlider {\n"
                     "    min-height: 20px;\n"
                     "    background: rgb(40, 40, 40);}\n"
                     "\n"
                     "QSlider::groove:horizontal {\n"
                     "    border: 0px;\n"
                     "    background: rgb(200, 200, 200);"
                     "    height: 20px;\n"
                     "    border-radius: 10px;}\n"
                     "\n"
                     "QSlider::handle {\n"
                     "    background: rgb(55, 55, 55);\n"
                     "    height: 20px;\n"
                     "    width: 20px;\n"
                     "    border-radius: 10px;}\n"
                     "\n"
                     "QSlider::sub-page:horizontal {\n"
                     "    background: rgb(100, 100, 100);\n"
                     "    border-top-left-radius: 10px;\n"
                     "    border-bottom-left-radius: 10px;}\n")


if __name__ == '__main__':
    print(MyThemes.white_central_widget)
